# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      - /app/vendor
    # environment:
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    depends_on:
      - dbgpproxy
    pull_policy: always
  dbgpproxy:
    container_name: dbgpproxy
    restart: always
    build:
      context: ./config/dbgpProxy
      dockerfile: Dockerfile
    environment:
      DBGP_PROXY_PORT: 9001
      XDEBUG_CLIENT_PORT: 9003
    ports:
      - target: 9001
        published: 9100
        protocol: tcp
    pull_policy: always
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
